import turtle
vivekdhir= turtle.Turtle()
vivekdhir.color("red",'yellow')
vivekdhir.speed(10)
vivekdhir.begin_fill()
vivekdhir.penup()
vivekdhir.backward(300)
vivekdhir.pendown()

vivekdhir.left(120)
vivekdhir.forward(50)
vivekdhir.right(180)
vivekdhir.forward(50)
vivekdhir.left(120)
vivekdhir.forward(50)
vivekdhir.right(180)
vivekdhir.forward(50)
vivekdhir.left(120)
vivekdhir.penup()
vivekdhir.forward(50)
vivekdhir.pendown()#V

vivekdhir.left(90)
vivekdhir.forward(50)
vivekdhir.penup()
vivekdhir.forward(10)
vivekdhir.pendown()
vivekdhir.forward(5)
vivekdhir.backward(2.5)
vivekdhir.right(90)
vivekdhir.forward(2.5)
vivekdhir.backward(5)
vivekdhir.forward(2.5)
vivekdhir.right(90)
vivekdhir.forward(2.5)
vivekdhir.penup()
vivekdhir.forward(10)
vivekdhir.pendown()
vivekdhir.forward(50)
vivekdhir.left(90)

vivekdhir.penup()
vivekdhir.forward(50)
vivekdhir.pendown()


vivekdhir.left(120)
vivekdhir.forward(50)
vivekdhir.right(180)
vivekdhir.forward(50)
vivekdhir.left(120)
vivekdhir.forward(50)
vivekdhir.right(180)
vivekdhir.forward(50)
vivekdhir.left(120)
vivekdhir.penup()
vivekdhir.forward(50)
vivekdhir.pendown()

vivekdhir.left(90)
vivekdhir.forward(50)
vivekdhir.right(90)
vivekdhir.forward(20)
vivekdhir.backward(22.5)
vivekdhir.right(90)
vivekdhir.forward(25)
vivekdhir.left(90)
vivekdhir.forward(20)
vivekdhir.backward(20)
vivekdhir.right(90)
vivekdhir.forward(25)
vivekdhir.left(90)
vivekdhir.forward(22.5)
vivekdhir.penup()
vivekdhir.forward(26)
vivekdhir.pendown()#E

vivekdhir.left(90)
vivekdhir.forward(50)
vivekdhir.backward(27)
vivekdhir.right(40)
vivekdhir.forward(30)
vivekdhir.backward(20)
vivekdhir.right(120)
vivekdhir.forward(35)#K

vivekdhir.left(70)
vivekdhir.penup()
vivekdhir.forward(25)
vivekdhir.pendown()

for i in range(13):
    vivekdhir.left(i)
    vivekdhir.forward(4)
    vivekdhir.left(i/2)
for i in range(10):
    vivekdhir.left(i)
    vivekdhir.forward(5)
    vivekdhir.left(i)
vivekdhir.left(65)
vivekdhir.forward(55)

vivekdhir.left(90)
vivekdhir.penup()
vivekdhir.forward(50)
vivekdhir.pendown()

vivekdhir.left(90)
vivekdhir.forward(50)
vivekdhir.backward(25)
vivekdhir.right(90)
vivekdhir.forward(35)
vivekdhir.left(90)
vivekdhir.forward(25)
vivekdhir.backward(50)
vivekdhir.right(90)

vivekdhir.penup()
vivekdhir.forward(25)
vivekdhir.pendown()

vivekdhir.forward(20)
vivekdhir.left(90)
vivekdhir.forward(45)
vivekdhir.left(90)
vivekdhir.forward(20)
vivekdhir.backward(40)
vivekdhir.forward(20)
vivekdhir.left(90)
vivekdhir.forward(45)
vivekdhir.left(90)
vivekdhir.forward(20)


vivekdhir.penup()
vivekdhir.forward(25)
vivekdhir.pendown()


vivekdhir.left(90)
vivekdhir.forward(50)
vivekdhir.backward(25)
vivekdhir.right(140)
vivekdhir.forward(37)
vivekdhir.backward(37)
vivekdhir.left(50)
for i in range(15):
    vivekdhir.left(i/2)
    vivekdhir.forward(3)
    vivekdhir.left(i)

vivekdhir.left(20)
vivekdhir.forward(23)

vivekdhir.left(94)
vivekdhir.forward(50)

turtle.done()
